import{NextResponse}from"next/server";import crypto from"node:crypto";import{db}from"@/lib/db/client";

export const runtime="nodejs";

function verifyStripeSignature(raw:string,header:string,secret:string){const parts=header.split(",");const timestamp=parts.find(p=>p.startsWith("t="))?.slice(2);const signatures=parts.filter(p=>p.startsWith("v1=")).map(p=>p.slice(3));if(!timestamp||!signatures.length)return false;const age=Math.abs(Math.floor(Date.now()/1000)-Number(timestamp));if(!Number.isFinite(age)||age>300)return false;const expected=crypto.createHmac("sha256",secret).update(timestamp+"."+raw).digest("hex");return signatures.some(sig=>sig.length===expected.length&&crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))}

function stringValue(value:unknown){return typeof value==="string"?value:null}
function recordValue(value:unknown){return value&&typeof value==="object"?value as Record<string,unknown>:{}}

export async function POST(req:Request){try{const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)return NextResponse.json({error:"Stripe webhook is not configured."},{status:503});const signature=req.headers.get("stripe-signature");if(!signature)return NextResponse.json({error:"Missing Stripe signature."},{status:400});const raw=await req.text();if(!verifyStripeSignature(raw,signature,secret))return NextResponse.json({error:"Invalid Stripe signature."},{status:400});let event:Record<string,unknown>;try{event=JSON.parse(raw)}catch{return NextResponse.json({error:"Invalid webhook payload."},{status:400})}const eventId=stringValue(event.id);const eventType=stringValue(event.type);if(!eventId||!eventType)return NextResponse.json({error:"Invalid Stripe event."},{status:400});const existing=await db.billingEvent.findUnique({where:{providerEventId:eventId},select:{id:true}});if(existing)return NextResponse.json({received:true,duplicate:true});

const data=recordValue(recordValue(event.data).object);const metadata=recordValue(data.metadata);let userId=stringValue(metadata.userId);const customerId=stringValue(data.customer);const subscriptionId=stringValue(data.id)||stringValue(data.subscription);
if(!userId&&customerId){const user=await db.subscription.findFirst({where:{providerCustomerId:customerId},select:{userId:true}});userId=user?.userId||null}
if((eventType==="customer.subscription.created"||eventType==="customer.subscription.updated"||eventType==="customer.subscription.deleted")&&userId&&subscriptionId){
 const status=stringValue(data.status)||"UNKNOWN";const plan=stringValue(metadata.plan)||"FREE";const periodEnd=typeof data.current_period_end==="number"?new Date(data.current_period_end*1000):null;
 await db.subscription.upsert({where:{providerSubscriptionId:subscriptionId},create:{userId,provider:"stripe",providerCustomerId:customerId,providerSubscriptionId:subscriptionId,plan,status,currentPeriodEnd:periodEnd},update:{userId,providerCustomerId:customerId,plan,status,currentPeriodEnd:periodEnd}});
}
if(eventType==="checkout.session.completed"&&userId){
 const subId=stringValue(data.subscription);const customer=customerId;const checkoutPlan=stringValue(metadata.plan)||"FREE";if(subId){const subscriptionResponse=await fetch("https://api.stripe.com/v1/subscriptions/"+encodeURIComponent(subId),{headers:{Authorization:"Bearer "+(process.env.STRIPE_SECRET_KEY||"")},cache:"no-store"});if(!subscriptionResponse.ok)throw new Error("Unable to verify completed Stripe subscription.");const stripeSubscription=recordValue(await subscriptionResponse.json());const stripeMetadata=recordValue(stripeSubscription.metadata);const verifiedUserId=stringValue(stripeMetadata.userId)||userId;const verifiedPlan=stringValue(stripeMetadata.plan)||checkoutPlan;const verifiedStatus=stringValue(stripeSubscription.status)||"incomplete";const verifiedPeriodEnd=typeof stripeSubscription.current_period_end==="number"?new Date(stripeSubscription.current_period_end*1000):null;await db.subscription.upsert({where:{providerSubscriptionId:subId},create:{userId:verifiedUserId,provider:"stripe",providerCustomerId:customer,providerSubscriptionId:subId,plan:verifiedPlan,status:verifiedStatus,currentPeriodEnd:verifiedPeriodEnd},update:{userId:verifiedUserId,providerCustomerId:customer,plan:verifiedPlan,status:verifiedStatus,currentPeriodEnd:verifiedPeriodEnd}})}
}
await db.billingEvent.create({data:{provider:"stripe",providerEventId:eventId,eventType}});return NextResponse.json({received:true})}catch(error){if((error as {code?:string})?.code==="P2002")return NextResponse.json({received:true,duplicate:true});console.error("Stripe webhook failed",error);return NextResponse.json({error:"Unable to process webhook."},{status:500})}}